export const ENV_KEYS = {
  LLM_PROVIDER: "LLM_PROVIDER",
  OPENAI_API_KEY: "OPENAI_API_KEY",
  OPENAI_MODEL: "OPENAI_MODEL",
  GEMINI_API_KEY: "GEMINI_API_KEY",
  GEMINI_MODEL: "GEMINI_MODEL",
  GROQ_API_KEY: "GROQ_API_KEY",
  GROQ_MODEL: "GROQ_MODEL",
} as const;
